// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksdvzuxekocqtqvqxjrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzZHZ6dXhla29jcXRxdnF4anJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTk1NzEsImV4cCI6MjA2ODgzNTU3MX0.nTBkDeOO2AWp9JgQWe45Zgj1xPNYu0cWZf7U8fjSa-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});